### ISSUE TITLE
(2.7.1) Python client blocks forever in "create_producer" during a broker failure, even if "operation_timeout_seconds" is set

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#10721]
**Describe the bug**

During some chaos testing of a Pulsar cluster I observed a case in which the Python client does not honor the "operation_timeout_secs" timeout field and blocks forever while talking to a failed broker.

Specifically, the "create_producer" RPC hangs indefinitely. 

**To Reproduce**

I have a pulsar cluster (2.7.1) configured via the stock Helm chart on EKS (5 brokers x 5 bookies x 1 zookeeper).

I turned off the LivenessProbe on the brokers once they all started, and run the broker as a subprocess of PID 1 rather than PID 1 itself.

I have a python client producing (synchronously) in a loop. Whenever it gets an error it re-creates its producer and its client object. The client has operation_timeout_seconds=10 set, and the producer has send_timeout_millis=1000 set.

For my chaos test, I start 100 clients producing, verify that everything is working normally,  and then, one by one, send SIGSTOP to the JVM process on all of my brokers except one.

**Expected behavior**
What I'd expect to happen is for, after some hiccups, my producers to all connect to the one remaining broker and produce to it.

What actually happens is that *many* (but not all) of my producers get stuck talking to the SIGSTOP'd brokers. If I replace the brokers after minutes/hours the producers wake up and start producing again.

By starting a watcher thread and checking what call my main thread is in the middle of, I can observe that "create_producer" is the call that blocks. 

The blocking situation stops when the failed brokers are restored to service. However, as long as the brokers remain failed, I have not observed a blocked client unblocked, and some of them have stayed stuck for hours. 

**Desktop (please complete the following information):**
 - Amazon Linux/EKS, current version.

**Comment by zbentley** [comment]
After SIGSTOPing brokers, I do see them disappear from the API listing and the manager UI for my cluster. That leads me to believe the problem lies in the client--either my code is misusing the pulsar client library, or the client library isn't re-discovering or timing out when it should.

`lsof` on my clients indicates some TCP sockets on 6650 to SIGSTOP'd brokers, and some to the healthy/remaining brokers. However, not all clients have sockets open to all brokers, alive or dead.

Attached are the thread stacks from a blocked client (thread 2 is an observer thread I started in order to log what call the main thread was stuck on). 

[stacks.txt](https://github.com/apache/pulsar/files/6550058/stacks.txt)

**Comment by BewareMyPower** [comment]
`create_producer` will first connect to the URL's broker for topic lookup. Currently C++/Python client only supports a single broker's advertised address, which broker did you connect to in your 5 brokers? And was this broker still available? If the broker for topic lookup was not available, the client wouldn't switch to another broker and the `ConnectError` should be reported for `create_producer`.

Could you collect and provide logs from a stuck producer?

Here's the python code I guessed, could you point out some differences from your code?

```python
import pulsar
import _pulsar
from pulsar.schema import *

client = pulsar.Client(service_url='pulsar://localhost:6650', operation_timeout_seconds=5)
producer = client.create_producer('my-topic', send_timeout_millis=1000, schema=StringSchema())

for i in range(0, 10000000):
    try:
        producer.send(str(i))
    except _pulsar.Timeout as e:
        print('Failed to send {}: {}'.format(i, e))
        producer = client.create_producer('my-topic', send_timeout_millis=1000)

client.close()
```

**Comment by BewareMyPower** [comment]
I just found that the TCP connection timeout is not included in operation timeout. I'm not sure what's your state of connection between the blocked client and its associated broker.

**Comment by zbentley** [comment]
Since I'm running on Kubernetes, a random broker would have been selected for topic lookup. I suspect that my blocked clients were connected to an unavailable broker, and that this:

> the `ConnectError` should be reported for create_producer.

Is not happening as it should.

I will collect logs from a stuck producer and post here shortly.

**Comment by BewareMyPower** [comment]
First I noticed there's a line in your log:

```
2021-05-28 19:57:42.121 WARN  [140473932080896[] PartitionedProducerImpl:369 | Failed to getPartitionMetadata: TimeOut
```

It could only be caused by operation timeout so there's nothing wrong with `operation_timeout_seconds`.

>  Since I'm running on Kubernetes, a random broker would have been selected for topic lookup. I suspect that my blocked clients were connected to an unavailable broker

I'm afraid it's not the cause because if the broker is not available, the connection could not be established, right? No topic lookup request could be sent if the connection was not established. In this case the error logs should be

```
 ClientImpl:<line-no> | Error Checking/Getting Partition Metadata while creating producer on <topic-name>
```

> In fairly short order, that code stopped emitting "Sent: " updates, and printed Reconnecting to producer, at which point it got stuck.

So the `Reconnecting to producer` log only occurred once? Then your program must stuck at `create_producer` and it's not caused by topic lookup. When a producer to a partitioned topic with N partitions is created, N internal producers will be created. However, only after all producers are created would `create_producer` be completed normally or exceptionally.

For example, the logs should have N following lines if all internal producers are created successfully.

```
ProducerImpl:<line-no> | [persistent://public/default/<topic>-partition-<partition-no>, ] Created producer on broker
```

I noticed your log is not completed, could you check how many internal producers were created after `Reconnecting to producer`? And is there any log like `Unable to create Producer for partition`?

**Comment by zbentley** [comment]
Yes, the program is stuck in the `create_producer` call. 

There are no log lines indicating "Unable to create Producer"; I believe it is either getting stuck before that or not flushing its output (while I'm running with PYTHONUNBUFFERED=1, that may not apply to whatever autoflush behavior is configured inside the C++ code). 

The fact that the producers become unstuck when the brokers are unpaused (unstopped) also indicates that there may be a missing connect timeout.

Attached is an entire unedited log segment recorded during the SIGSTOP of a single broker. These logs were generated in a foreground PTY (no kubernetes swallowing/buffering output). The code used is exactly the code copied above with no changes. The logs below showed no activity for more than 5 minutes.

[logs_f.txt](https://github.com/apache/pulsar/files/6577581/logs_f.txt)

**Comment by zbentley** [comment]
Any update here? I know it may take some time to fix, but it'd be useful to know if it is likely to be worked on or not.

Whether this gets fixed is the difference between whether our site uses the Python driver normally, or puts some engineering time into moving the Pulsar connection(s) out-of-process and communicating with them via RPC. Either one is fine, but would rather not start down one path and have to abandon it.

Thanks, and sorry to nag!

**Comment by BewareMyPower** [comment]
Sorry for the late response. Just missed this issue since I was not assigned before and I was busy last week. Now I'll assign it to myself and continue looking at this issue. 

From my perspective, your comment at https://github.com/apache/pulsar/issues/10747 is correct. Currently we cannot configure connection timeout and I'll add this config first.

**Comment by BewareMyPower** [comment]
Hi, could you provide your boost version?

**Comment by zbentley** [comment]
I don't know; how would I find out? I'm using the result of `pip install pulsar-client==2.7.1` on the docker python3.8 image.

```
root@4d281df6a62c:/usr/local/lib/python3.8/site-packages# ldd _pulsar.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffdf09fc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2fc3819000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2fc3814000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2fc380a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2fc3687000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2fc34c6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2fc42f9000)
root@4d281df6a62c:/usr/local/lib/python3.8/site-packages# dpkg -l | grep boost
root@4d281df6a62c:/usr/local/lib/python3.8/site-packages# find / | grep boost
/proc/sys/vm/watermark_boost_factor
```

**Comment by BewareMyPower** [comment]
That's okay, I'm just going to get more info from your stacks.

**Comment by BewareMyPower** [comment]
I'm currently working on the connection timeout, but I found something confused from your logs.

Here're my analysis from your logs (logs_f.txt):

```bash
# "Created connection" means the socket object was created and started to connect.
# **connection** means the ClientConnection object that contains a socket and other fields, not the real TCP connection.
2021-06-01 15:48:49.554 INFO  [140607179827008] ConnectionPool:84 | Created connection for pulsar://pulsar-blt-broker.broker-load-test-blt:6650
# "Connected to broker" means the TCP connection was established successfully.
2021-06-01 15:48:49.556 INFO  [140607120344832] ClientConnection:364 | [10.0.181.183:44014 -> 10.0.187.196:6650] Connected to broker
# After about 40 seconds, the connection closed.  It's because no PONG command has been received from broker
# for 30 seconds after the client sent the PING command to broker.
.2021-06-01 15:49:37.816 WARN  [140607145748224] ClientConnection:1368 | [10.0.181.183:43844 -> 10.0.187.196:6650] Forcing connection to close after keep-alive timeout
2021-06-01 15:49:37.816 INFO  [140607145748224] ClientConnection:1436 | [10.0.181.183:43844 -> 10.0.187.196:6650] Connection closed
```

The conclusion is that the client connected to a broker successfully and quickly (15:48:49.556 - 15:48:49.554 = 2 milliseconds), but received no responses from broker.

What I'm confused is, the last line of `logs_f.txt` is

```
2021-06-01 15:49:37.935 INFO  [140607145748224] ProducerImpl:170 | [persistent://public/default/foobar-partition-25, pulsar-blt-102-8] Created producer on broker [10.0.181.183:36136 -> 10.0.178.77:6650]
```

It's less than 1 minutes from the time point you stopped your broker, see

> In this log segment, the broker was killed at 15:48:46

And the last line of your logs means your produce has been created successfully. So I don't understand

> The logs below showed no activity for more than 5 minutes.

BTW, could you enable debug logging and test again? You can take https://github.com/apache/pulsar/pull/7713 for example.

```python
import logging
import pulsar

class Client:
    def __init__(self):
        self.client = pulsar.Client(
            service_url='pulsar://pulsar-blt-broker.broker-load-test-blt:6650',
            operation_timeout_seconds=5,
            logger=logging.getLogger("pulsar")
        )

    def get_producer(self):
        return self.client.create_producer(
            'foobar',
            block_if_queue_full=True,
            send_timeout_millis=1000,
            batching_enabled=False
        )
        
    def run(self):
        producer = self.get_producer()
        # TODO: add your logic here

    def close(self):
        self.client.close()

if __name__ == '__main__':
    # Write the debug level logs to debug.log file
    logging.basicConfig(filename="debug.log", encoding='utf-8', level=logging.DEBUG)
    client = Client()
    client.run()
    client.close()
```

**Comment by zbentley** [comment]
@BewareMyPower I will re-test using the code you provided (I will have to alter it slightly to reconnect/re-create producers whenever an error occurs) next week. Thanks for digging into this!

In response to your other question: when I said

> The logs below showed no activity for more than 5 minutes.

I meant that, after that log line, no subsequent lines indicating successful publishes could be seen; my main loop had stopped. Using gdb and pdb indicated that it was stuck inside the call to `create_producer`. So basically: you're right that the pulsar client internals wrote a log line indicating successful producer creation, but that line being written didn't seem to cause `create_producer` to return--something (chronologically or in code) after that logger call blocked and prevented return.

**Comment by BewareMyPower** [comment]
Okay, so the program stuck at `create_producer` for 5 minutes after all logs?

BTW, I suspect there's something wrong with the topics auto delete policy. Could you modify your broker's config to the following config before re-testing?

```properties
brokerDeleteInactiveTopicsEnabled=false
```

I noticed that you created a producer of a partitioned topic that has 31 partitions, right?

```
2021-06-01 15:47:37.818 INFO  [140607145748224] HandlerBase:54 | [persistent://public/default/foobar-partition-0, ] Getting connection from pool
...
2021-06-01 15:47:37.818 INFO  [140607145748224] HandlerBase:54 | [persistent://public/default/foobar-partition-31, ] Getting connection from pool
```

It's a little weird that only 25 partitions were associated with producers successfully but the producer still worked well before a broker was stopped.

```
2021-06-01 15:47:37.826 INFO  [140607145748224] ProducerImpl:170 | [persistent://public/default/foobar-partition-1, ] Created producer on broker [10.0.181.183:40766 -> 10.0.177.109:6650]
# 23 lines...
2021-06-01 15:47:37.837 INFO  [140607145748224] ProducerImpl:170 | [persistent://public/default/foobar-partition-11, ] Created producer on broker [10.0.181.183:55478 -> 10.0.185.97:6650]
```

The partitions are [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 28, 30, 31] after sorted. Then [13, 17, 21, 25, 28] of them were not available and the client reconnect. Though these 5 partitions were associated with producers eventually, the `create_producer` didn't return.

I'll take a further look at this issue. And when you're altering my code, if you're going to recreate a producer, it's better to close the original producer first. i.e.

```python
    def run(self):
        producer = self.get_producer()
        # TODO: add your logic here
        if (encounter_failure()):
          producer.close()
          producer = self.get_producer()
```

**Comment by zbentley** [comment]
My topic had 32 partitions, yes. 

All tests are already being run with `brokerDeleteInactiveTopicsEnabled: "false"` in the Helm chart (and I repeatedly seenthat it's working and that topics are not being deleted between test runs).

When I'm back at work next week, I'll adapt your test code and be sure to issue a "close" on the producer in the event of a failure. I'd hope that doing a close RPC exchange isn't required in order to prevent stuckness, however.

**Comment by BewareMyPower** [comment]
I've also pushed a PR to add the connection timeout: https://github.com/apache/pulsar/pull/11029, though it might not be the real cause of your issue.

**Comment by zbentley** [comment]
@BewareMyPower thanks, still tracking this issue on my side, but I can't work your proposed reproduction steps in this sprint; will update here when I have more findings.

**Comment by zbentley** [comment]
Sorry for taking so long to come back to this. I was able to reproduce the issue on 2.8.0 with the `2.8.0.post0` Python client 
 (MacOS 10.11, Python 3.6.9).

Better yet, I was able to reproduce it against standalone broker with the below snippet, no partitioned topic or multi-node ensemble required.

Additionally, another symptom of this bug is that if the below snippet is launched after the broker is SIGSTOPped, it hangs (does not respect `operation_timeout_secs`) on startup, after printing `Connected to Broker`.

```
import sys
import pulsar

clients = []

def logflush(msg):
    print(msg)
    sys.stdout.flush()
    sys.stderr.flush()

def get_producer():
    try:
        cl = pulsar.Client(
            'pulsar://localhost:6650',
            operation_timeout_seconds=1,
        )
        clients.append(cl)  # intentionally leak clients on reconnect to prevent segfaults per https://github.com/apache/pulsar/issues/6463
        rv = cl.create_producer('foobar')
        logflush('Created producer')
        return rv
    except Exception as e:
        logflush('error creating producer: {}'.format(e))
        raise


producer = get_producer()
sent = 0
while True:
    try:
        producer.send(b'foo')
        sent += 1
        if sent % 1000 == 0:
            logflush('Sent: {}'.format(sent))
    except Exception as e:
        logflush('Got exception: {}'.format(e))
        producer = get_producer()
```

When I `kill -SIGSTOP` the standalone broker's PID, the Python client hangs. I waited for 120sec for any logs to be emitted and attached them below, and also grabbed a `bt all` stack report from LLDB.

Here are those:
[logs.txt](https://github.com/apache/pulsar/files/7086726/logs.txt)
[stacks.txt](https://github.com/apache/pulsar/files/7086727/stacks.txt)

**Comment by zbentley** [comment]
On master, which has merged https://github.com/apache/pulsar/pull/11029, the issue still occurs. I built _pulsar.so against `master` and re-ran the above snippet twice: once against a running broker that I SIGSTOPped, and once against an already SIGSTOPped broker.

Both runs exhibited the bug (both uninterruptibly hung), though the first run emitted more logs and retried internally while on `master`.

It seems like the Pulsar client really wants to handle internal connect retries, but that interacts poorly with assumptions made by single-threaded calling code, like Python.

Is it possible to disable that functionality entirely? I.e. let the Python Client/producer/consumer objects represent a single open socket upstream directly, rather than a lazy object that the Pulsar client may internally connect/disconnect on a socket whenever it wants? I'd happily make that trade (having to handle reconnects etc.) in exchange for knowing that client operations would reliably time out when things go wrong.

Here are the logs and stacks from the one that ran during the SIGSTOP:
[logs.txt](https://github.com/apache/pulsar/files/7087087/logs.txt)
[stacks.txt](https://github.com/apache/pulsar/files/7087088/stacks.txt)

And here are the logs and stacks from the one that I ran against an already SIGSTOPped broker:
[logs.txt](https://github.com/apache/pulsar/files/7087096/logs.txt)
[stacks.txt](https://github.com/apache/pulsar/files/7087097/stacks.txt)

**Comment by BewareMyPower** [comment]
I still cannot reproduce the bug. For the first log file, it looks like the reconnection logs only happened for `send`, instead of `create_producer`. I ran your code with a little change that adds the timeout for send

```python
        rv = cl.create_producer('foobar', send_timeout_millis=1000)
```

Here's the output:

```
Sent: 2000
Sent: 3000
2021-09-01 11:02:40.385 INFO  [0x7000048d7000] HandlerBase:142 | [persistent://public/default/foobar, standalone-6-0] Schedule reconnection in 0.1 s
2021-09-01 11:02:40.394 ERROR [0x7000048d7000] ClientConnection:572 | [127.0.0.1:59743 -> 127.0.0.1:6650] Read failed: End of file
2021-09-01 11:02:40.394 INFO  [0x7000048d7000] ClientConnection:1495 | [127.0.0.1:59743 -> 127.0.0.1:6650] Connection closed
2021-09-01 11:02:40.487 INFO  [0x7000048d7000] HandlerBase:64 | [persistent://public/default/foobar, standalone-6-0] Getting connection from pool
2021-09-01 11:02:40.487 INFO  [0x7000048d7000] ConnectionPool:86 | Deleting stale connection from pool for pulsar://localhost:6650 use_count: 1 @ 0x7fae5580c000
2021-09-01 11:02:40.487 INFO  [0x7000048d7000] ClientConnection:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-09-01 11:02:40.487 INFO  [0x7000048d7000] ConnectionPool:96 | Created connection for pulsar://localhost:6650
2021-09-01 11:02:40.489 ERROR [0x7000048d7000] ClientConnection:448 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2021-09-01 11:02:40.489 INFO  [0x7000048d7000] ClientConnection:1495 | [<none> -> pulsar://localhost:6650] Connection closed
2021-09-01 11:02:40.489 INFO  [0x7000048d7000] HandlerBase:142 | [persistent://public/default/foobar, standalone-6-0] Schedule reconnection in 0.182 s
2021-09-01 11:02:40.676 INFO  [0x7000048d7000] HandlerBase:64 | [persistent://public/default/foobar, standalone-6-0] Getting connection from pool
2021-09-01 11:02:40.676 INFO  [0x7000048d7000] ConnectionPool:86 | Deleting stale connection from pool for pulsar://localhost:6650 use_count: 1 @ 0x7fae54852800
2021-09-01 11:02:40.676 INFO  [0x7000048d7000] ClientConnection:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-09-01 11:02:40.676 INFO  [0x7000048d7000] ConnectionPool:96 | Created connection for pulsar://localhost:6650
2021-09-01 11:02:40.678 ERROR [0x7000048d7000] ClientConnection:448 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2021-09-01 11:02:40.678 INFO  [0x7000048d7000] ClientConnection:1495 | [<none> -> pulsar://localhost:6650] Connection closed
2021-09-01 11:02:40.678 INFO  [0x7000048d7000] HandlerBase:142 | [persistent://public/default/foobar, standalone-6-0] Schedule reconnection in 0.372 s
2021-09-01 11:02:41.052 INFO  [0x7000048d7000] HandlerBase:64 | [persistent://public/default/foobar, standalone-6-0] Getting connection from pool
2021-09-01 11:02:41.052 INFO  [0x7000048d7000] ConnectionPool:86 | Deleting stale connection from pool for pulsar://localhost:6650 use_count: 1 @ 0x7fae5384e800
2021-09-01 11:02:41.052 INFO  [0x7000048d7000] ClientConnection:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-09-01 11:02:41.052 INFO  [0x7000048d7000] ConnectionPool:96 | Created connection for pulsar://localhost:6650
2021-09-01 11:02:41.054 ERROR [0x7000048d7000] ClientConnection:448 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2021-09-01 11:02:41.054 INFO  [0x7000048d7000] ClientConnection:1495 | [<none> -> pulsar://localhost:6650] Connection closed
2021-09-01 11:02:41.054 INFO  [0x7000048d7000] HandlerBase:142 | [persistent://public/default/foobar, standalone-6-0] Schedule reconnection in 0.224 s
2021-09-01 11:02:41.281 INFO  [0x7000048d7000] HandlerBase:64 | [persistent://public/default/foobar, standalone-6-0] Getting connection from pool
2021-09-01 11:02:41.281 INFO  [0x7000048d7000] ConnectionPool:86 | Deleting stale connection from pool for pulsar://localhost:6650 use_count: 1 @ 0x7fae5305ce00
2021-09-01 11:02:41.281 INFO  [0x7000048d7000] ClientConnection:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-09-01 11:02:41.281 INFO  [0x7000048d7000] ConnectionPool:96 | Created connection for pulsar://localhost:6650
2021-09-01 11:02:41.283 ERROR [0x7000048d7000] ClientConnection:448 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2021-09-01 11:02:41.283 INFO  [0x7000048d7000] ClientConnection:1495 | [<none> -> pulsar://localhost:6650] Connection closed
2021-09-01 11:02:41.283 INFO  [0x7000048d7000] HandlerBase:142 | [persistent://public/default/foobar, standalone-6-0] Schedule reconnection in 1.568 s
Got exception: Pulsar error: TimeOut
2021-09-01 11:02:41.390 INFO  [0x118051e00] ClientConnection:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-09-01 11:02:41.390 INFO  [0x118051e00] ConnectionPool:96 | Created connection for pulsar://localhost:6650
2021-09-01 11:02:41.392 ERROR [0x7000049dd000] ClientConnection:448 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2021-09-01 11:02:41.392 INFO  [0x7000049dd000] ClientConnection:1495 | [<none> -> pulsar://localhost:6650] Connection closed
2021-09-01 11:02:41.392 ERROR [0x7000049dd000] ClientImpl:188 | Error Checking/Getting Partition Metadata while creating producer on persistent://public/default/foobar -- ConnectError
error creating producer: Pulsar error: ConnectError
```

The reconnection related logs should appear before the `Got exception: Pulsar error: TimeOut` line, but it appeared after this line in your logs. It might be caused by the stdout not synchronized. During `create_producer`, there should be no logs printed by `HandlerBase`.

I suspected there's something wrong with the phase to establish connection because your logs don't contain `Error Checking/Getting Partition Metadata`. `create_producer` performs topic lookup at first, so if the connection cannot be established, the topic lookup will fail.

Since you built source from master, you can add connection timeout and try again.

```python
        cl = pulsar.Client(
            'pulsar://localhost:6650',
            operation_timeout_seconds=1,
            connection_timeout_ms=1000,
        )
```

> once against an already SIGSTOPped broker.

Regarding to this case, could you enable debug logs and try again?

**Comment by zbentley** [comment]
OK, I modified my code to the following:
```
import pulsar
import logging

logging.basicConfig(filename='debug.log', level=logging.DEBUG)
clients = []

def log(m):
    logging.debug(m)

def get_producer():
    try:
        cl = pulsar.Client(
            'pulsar://localhost:6650',
            operation_timeout_seconds=1,
            connection_timeout_ms=1000,
            logger=logging.getLogger(),
        )
        clients.append(cl)  # intentionally leak clients on reconnect to prevent segfaults per https://github.com/apache/pulsar/issues/6463
        log('Creating producer')
        rv = cl.create_producer('foobar', send_timeout_millis=1000)
        log('Created producer')
        return rv
    except Exception as e:
        log('Error creating producer: {}'.format(e))
        raise


producer = get_producer()
sent = 0
while True:
    try:
        producer.send(b'foo')
        sent += 1
        if sent % 1000 == 0:
            log('Sent: {}'.format(sent))
    except Exception as e:
        log('Got exception: {}'.format(e))
        producer = get_producer()
```

I ran once with a running broker that was SIGSTOPped. The kill command was `pkill -SIGSTOP -f pulsar; echo -e '\nKILLED HERE\n' >> debug.log`, so the logs should contain that string when it happened.

Here is the debug log file (I waited a couple minutes before shutting down my script):

[debug.log](https://github.com/apache/pulsar/files/7091645/debug.log)

And here is the debug log (emptied out from the previous test) run when attempting to start my script against an already SIGSTOPped broker:

[debug.log](https://github.com/apache/pulsar/files/7091686/debug.log)

**Comment by BewareMyPower** [comment]
I found the reason why I can't reproduce it. Because I used to just type Ctrl+C to stop the standalone. With your provided command:

```
pkill -SIGSTOP -f pulsar
```

Now I can reproduce this issue in my local env. I'll look into this issue for the solution.

**Comment by BewareMyPower** [comment]
It's a bug of connect timeout. I'll push the fix soon.
