### ISSUE TITLE
Broken links for pulsar-io-jdbc-2.6.0.nar.* on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/pulsar#7313]
The links for pulsar-io-jdbc-2.6.0.nar are broken.

**Comment by tuteng** [comment]
@sebbASF Thanks, It seems that jdbc's connector package has been split into multiple packages https://dist.apache.org/repos/dist/release/pulsar/pulsar-2.6.0/connectors/. We may need to consider fix this page http://pulsar.apache.org/en/download/. Currently, you can find the correct package from here https://dist.apache.org/repos/dist/release/pulsar/pulsar-2.6.0/connectors/.

**Comment by jiazhai** [comment]
@Jennifer88huang @Anonymitaet to help on this issue.

**Comment by Anonymitaet** [comment]
@tuteng 

1. Links on this page are generated automatically w/ each release?
![image](https://user-images.githubusercontent.com/50226895/85389127-9beea500-b579-11ea-9484-452dfe750004.png)

2. Can we modify the links on this page manually?

**Comment by tuteng** [comment]
ping @zeo1995 help fix this.

**Comment by tuteng** [comment]
@Anonymitaet @Jennifer88huang You can try to update this file https://github.com/apache/pulsar/blob/master/site2/website/data/connectors.js and replace the correct package

**Comment by Anonymitaet** [comment]
@tuteng seems that this file https://github.com/apache/pulsar/blob/master/site2/website/data/connectors.js only contains the link to each connector, but does not contain the download links of each connector.

![image](https://user-images.githubusercontent.com/50226895/85560214-062c4600-b65d-11ea-9c20-bf1ef07571bd.png)

**Comment by tuteng** [comment]
The download link is automatically generated based on the name

**Comment by vzhikserg** [comment]
@tuteng @jiazhai  I fixed the source, but the download page should be regenerated for the 2.6.0 release.

**Comment by tuteng** [comment]
Thanks for your contributing @vzhikserg It seems to build failed

```
/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:67
    throw new Error("No 'original_id' field found in ".concat(file, ". Perhaps you forgot to add it when importing prior versions of your docs?"));
    ^

Error: No 'original_id' field found in /pulsar/site2/website/versioned_docs/version-2.6.0/io-use.md. Perhaps you forgot to add it when importing prior versions of your docs?
    at forEach (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:64:11)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:52:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/pulsar/site2/website/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/pulsar/site2/website/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I will fixed this

**Comment by vzhikserg** [comment]
@tuteng good, thanks for checking it out and fixing the build of the website ;)

**Comment by THX1188** [comment]
When will the download page be fixed? Link for jdbc still not works.
cheers

**Comment by tuteng** [comment]
Yes, It is work, please try to refresh download page http://pulsar.apache.org/en/download/
